/* parser generated by jison 0.4.18 */
/*
  Returns a Parser object of the following structure:

  Parser: {
    yy: {}
  }

  Parser.prototype: {
    yy: {},
    trace: function(),
    symbols_: {associative list: name ==> number},
    terminals_: {associative list: number ==> name},
    productions_: [...],
    performAction: function anonymous(yytext, yyleng, yylineno, yy, yystate, $$, _$),
    table: [...],
    defaultActions: {...},
    parseError: function(str, hash),
    parse: function(input),

    lexer: {
        EOF: 1,
        parseError: function(str, hash),
        setInput: function(input),
        input: function(),
        unput: function(str),
        more: function(),
        less: function(n),
        pastInput: function(),
        upcomingInput: function(),
        showPosition: function(),
        test_match: function(regex_match_array, rule_index),
        next: function(),
        lex: function(),
        begin: function(condition),
        popState: function(),
        _currentRules: function(),
        topState: function(),
        pushState: function(condition),

        options: {
            ranges: boolean           (optional: true ==> token location info will include a .range[] member)
            flex: boolean             (optional: true ==> flex-like lexing behaviour where the rules are tested exhaustively to find the longest match)
            backtrack_lexer: boolean  (optional: true ==> lexer regexes are tested in order and for each matching regex the action code is invoked; the lexer terminates the scan when a token is returned by the action code)
        },

        performAction: function(yy, yy_, $avoiding_name_collisions, YY_START),
        rules: [...],
        conditions: {associative list: name ==> set},
    }
  }


  token location info (@$, _$, etc.): {
    first_line: n,
    last_line: n,
    first_column: n,
    last_column: n,
    range: [start_number, end_number]       (where the numbers are indexes into the input string, regular zero-based)
  }


  the parseError function receives a 'hash' object with these members for lexer and parser errors: {
    text:        (matched text)
    token:       (the produced terminal token, if any)
    line:        (yylineno)
  }
  while parser (grammar) errors will also provide these members, i.e. parser errors deliver a superset of attributes: {
    loc:         (yylloc)
    expected:    (string describing the set of expected tokens)
    recoverable: (boolean: TRUE when the parser has a error recovery rule available for this particular error)
  }
*/
var parser = (function(){
var o=function(k,v,o,l){for(o=o||{},l=k.length;l--;o[k[l]]=v);return o},$V0=[1,13],$V1=[1,14],$V2=[1,15],$V3=[1,16],$V4=[1,17],$V5=[1,19],$V6=[10,14,16,18,21,25],$V7=[1,24],$V8=[1,26],$V9=[1,30],$Va=[10,14,16,18,21,25,33,34,53],$Vb=[1,48],$Vc=[1,43],$Vd=[1,44],$Ve=[1,45],$Vf=[1,46],$Vg=[1,36],$Vh=[1,40],$Vi=[1,47],$Vj=[1,52],$Vk=[10,14,16,18,21,25,33,34,37,38,53],$Vl=[10,14,16,18,21,25,33,34];
var parser = {trace: function trace () { },
yy: {},
symbols_: {"error":2,"run":3,"scene":4,"EOF":5,"export":6,"EXPORT":7,"OBRACE":8,"statements":9,"CBRACE":10,"SCENE":11,"statement":12,"PASS":13,"IMPORT":14,"string":15,"ADD":16,"class":17,"SET":18,"VARNAME":19,"value":20,"DEFINE":21,"class_name":22,"EXTENDS":23,"function":24,"FUNC_NAME":25,"ARROW":26,"args":27,"KEYWORD":28,"vec3":29,"VEC3":30,"OPAR":31,"NUMBER":32,"COLON":33,"CPAR":34,"STRING":35,"unit":36,"DEG":37,"RAD":38,"array":39,"OARR":40,"numbers":41,"CARR":42,"strings":43,"number":44,"hexadecimal":45,"HEXA6":46,"HEXA8":47,"arg":48,"SCOPE_VARIABLE":49,"constant":50,"BOOL":51,"expression":52,"OPERATOR":53,"CONSTANT":54,"$accept":0,"$end":1},
terminals_: {2:"error",5:"EOF",7:"EXPORT",8:"OBRACE",10:"CBRACE",11:"SCENE",13:"PASS",14:"IMPORT",16:"ADD",18:"SET",19:"VARNAME",21:"DEFINE",23:"EXTENDS",25:"FUNC_NAME",26:"ARROW",28:"KEYWORD",30:"VEC3",31:"OPAR",32:"NUMBER",33:"COLON",34:"CPAR",35:"STRING",37:"DEG",38:"RAD",40:"OARR",42:"CARR",46:"HEXA6",47:"HEXA8",49:"SCOPE_VARIABLE",51:"BOOL",53:"OPERATOR",54:"CONSTANT"},
productions_: [0,[3,2],[3,2],[3,1],[6,4],[4,4],[9,2],[9,1],[9,1],[12,2],[12,2],[12,2],[12,3],[12,7],[12,1],[24,3],[22,1],[17,4],[17,1],[29,8],[29,8],[36,1],[36,1],[39,3],[39,3],[41,3],[41,1],[45,1],[45,1],[44,2],[44,1],[43,3],[43,1],[15,1],[27,3],[27,1],[48,2],[20,1],[20,1],[20,1],[20,1],[20,1],[20,1],[20,1],[20,1],[20,3],[52,5],[50,1]],
performAction: function anonymous(yytext, yyleng, yylineno, yy, yystate /* action[1] */, $$ /* vstack */, _$ /* lstack */) {
/* this == yyval */

var $0 = $$.length - 1;
switch (yystate) {
case 1: case 2:
 return $$[$0-1]; 
break;
case 3:
 /* skip */ 
break;
case 4: case 23: case 24:
 this.$ = $$[$0-1]; 
break;
case 5:
 this.$ = new yy.Scene({}, $$[$0-1]); 
break;
case 6:

                if ($$[$0][0] == 'import') {
                    Array.prototype.push.apply(this.$, $$[$0][1]);    
                } else {
                    this.$.push($$[$0]);
                }
            
break;
case 7:

                this.$ = [];
                
                if ($$[$0][0] == 'import') {
                    Array.prototype.push.apply(this.$, $$[$0][1]);
                } else {
                    this.$.push($$[$0]);
                }
            
break;
case 8:
 this.$ = []; 
break;
case 9:
 this.$ = [ 'import', yy.GetAST($$[$0]) ]; 
break;
case 10:
 this.$ = [ '2addClass', $$[$0] ]; 
break;
case 11:
 this.$ = [ '3setClass', $$[$0] ]; 
break;
case 12:
 this.$ = [
                '0setVariable', 
                [ $$[$0-1].replace(/=/, '').trim(), $$[$0], _$[$0-2].first_line ] 
            ];
break;
case 13:

                this.$ = [ '1extendClass', [ $$[$0-5], $$[$0-3], $$[$0-1] ] ];
            
break;
case 14: case 16:
 this.$ = $$[$0]; 
break;
case 15:

                this.$ = [ $$[$0-2].trim(), $$[$0] ];
            
break;
case 17:
 this.$ = [ $$[$0-3], $$[$0-1] ]; 
break;
case 18:
 this.$ = [ $$[$0], [] ]; 
break;
case 19:
 
                this.$ = new yy.Vec3 (
                    parseFloat($$[$0-5]), 
                    parseFloat($$[$0-3]),
                    parseFloat($$[$0-1])
                );
            
break;
case 20:
 this.$ = new yy.Vec3 ( $$[$0-5], $$[$0-3], $$[$0-1] ); 
break;
case 21:
 this.$ = parseFloat(0.0174533); 
break;
case 22:
 this.$ = parseFloat(1); 
break;
case 25:
 this.$.push( parseFloat($$[$0]) ); 
break;
case 26: case 32:
 this.$ = [$$[$0]]; 
break;
case 27:

                this.$ = parseInt($$[$0].replace(/0x/, ''), 16); 
                this.$ = new yy.Color (
                    (this.$ >> 16) & 255, (this.$ >> 8) & 255, (this.$ >> 0) & 255, 255
                );
            
break;
case 28:

                this.$ = parseInt($$[$0].replace(/0x/, ''), 16); 
                this.$ = new yy.Color (
                    (this.$ >> 24) & 255, (this.$ >> 16) & 255, (this.$ >> 8) & 255, (this.$ >> 0) & 255,
                );
            
break;
case 29:
 this.$ = $$[$0-1] * $$[$0]; 
break;
case 30:
 this.$ = parseFloat($$[$0]); 
break;
case 31:
 this.$.push('$$[$0]'); 
break;
case 33:
 this.$ = $$[$0].replace(/'/g, ''); 
break;
case 34:
 Object.assign(this.$, $$[$0]); 
break;
case 35:
 this.$ = {}; Object.assign(this.$, $$[$0]); 
break;
case 36:
 this.$ = { [`${$$[$0-1].replace(/=/g, '')}`]: $$[$0] }; 
break;
case 37:
 this.$ = [ 'const', parseFloat($$[$0]) ]; 
break;
case 38:
 this.$ = [ 'var', $$[$0].replace(/./, '') ]; 
break;
case 39: case 40: case 41: case 43:
 this.$ = [ 'const', $$[$0] ]; 
break;
case 42:
 this.$ = [ 'const', $$[$0] == 'true' ]; 
break;
case 44:
 this.$ = [ 'expr', $$[$0] ]; 
break;
case 45:
 this.$ = [ 'func', $$[$0-1] ]; 
break;
case 46:
 this.$ = [ $$[$0-2], [ $$[$0-3], $$[$0-1] ] ]; 
break;
case 47:
 this.$ = yy.Constants[$$[$0].replace(/ogl./g, '')]; 
break;
}
},
table: [{3:1,4:2,5:[1,4],6:3,7:[1,6],11:[1,5]},{1:[3]},{5:[1,7]},{5:[1,8]},{1:[2,3]},{8:[1,9]},{8:[1,10]},{1:[2,1]},{1:[2,2]},{9:11,12:12,13:$V0,14:$V1,16:$V2,18:$V3,21:$V4,24:18,25:$V5},{9:20,12:12,13:$V0,14:$V1,16:$V2,18:$V3,21:$V4,24:18,25:$V5},{10:[1,21],12:22,14:$V1,16:$V2,18:$V3,21:$V4,24:18,25:$V5},o($V6,[2,7]),o($V6,[2,8]),{15:23,35:$V7},{17:25,28:$V8},{17:27,19:[1,28],28:$V8},{22:29,28:$V9},o($V6,[2,14]),{26:[1,31]},{10:[1,32],12:22,14:$V1,16:$V2,18:$V3,21:$V4,24:18,25:$V5},{5:[2,5]},o($V6,[2,6]),o($V6,[2,9]),o($Va,[2,33]),o($V6,[2,10]),o($V6,[2,18],{8:[1,33]}),o($V6,[2,11]),{15:39,20:34,29:41,30:$Vb,31:$Vc,32:$Vd,35:$V7,44:35,45:37,46:$Ve,47:$Vf,49:$Vg,50:38,51:$Vh,52:42,54:$Vi},{23:[1,49]},o([8,23],[2,16]),{19:$Vj,27:50,48:51},{5:[2,4]},{9:53,12:12,13:$V0,14:$V1,16:$V2,18:$V3,21:$V4,24:18,25:$V5},o($V6,[2,12]),o($Va,[2,37],{36:54,37:[1,55],38:[1,56]}),o($Va,[2,38]),o($Va,[2,39]),o($Va,[2,40]),o($Va,[2,41]),o($Va,[2,42]),o($Va,[2,43]),o($Va,[2,44]),{15:39,20:58,24:57,25:$V5,29:41,30:$Vb,31:$Vc,32:$Vd,35:$V7,44:35,45:37,46:$Ve,47:$Vf,49:$Vg,50:38,51:$Vh,52:42,54:$Vi},o($Vk,[2,30]),o($Va,[2,27]),o($Va,[2,28]),o($Va,[2,47]),{31:[1,59]},{22:60,28:$V9},o([10,14,16,18,21,25,34],[2,15],{33:[1,61]}),o($Vl,[2,35]),{15:39,20:62,29:41,30:$Vb,31:$Vc,32:$Vd,35:$V7,44:35,45:37,46:$Ve,47:$Vf,49:$Vg,50:38,51:$Vh,52:42,54:$Vi},{10:[1,63],12:22,14:$V1,16:$V2,18:$V3,21:$V4,24:18,25:$V5},o($Vk,[2,29]),o($Vk,[2,21]),o($Vk,[2,22]),{34:[1,64]},{53:[1,65]},{32:[1,66],35:[1,67]},{8:[1,68]},{19:$Vj,48:69},o($Vl,[2,36]),o($V6,[2,17]),o($Va,[2,45]),{15:39,20:70,29:41,30:$Vb,31:$Vc,32:$Vd,35:$V7,44:35,45:37,46:$Ve,47:$Vf,49:$Vg,50:38,51:$Vh,52:42,54:$Vi},{33:[1,71]},{33:[1,72]},{9:73,12:12,13:$V0,14:$V1,16:$V2,18:$V3,21:$V4,24:18,25:$V5},o($Vl,[2,34]),{34:[1,74]},{32:[1,75]},{35:[1,76]},{10:[1,77],12:22,14:$V1,16:$V2,18:$V3,21:$V4,24:18,25:$V5},o($Va,[2,46]),{33:[1,78]},{33:[1,79]},o($V6,[2,13]),{32:[1,80]},{35:[1,81]},{34:[1,82]},{34:[1,83]},o($Va,[2,19]),o($Va,[2,20])],
defaultActions: {4:[2,3],7:[2,1],8:[2,2],21:[2,5],32:[2,4]},
parseError: function parseError (str, hash) {
    if (hash.recoverable) {
        this.trace(str);
    } else {
        var error = new Error(str);
        error.hash = hash;
        throw error;
    }
},
parse: function parse(input) {
    var self = this, stack = [0], tstack = [], vstack = [null], lstack = [], table = this.table, yytext = '', yylineno = 0, yyleng = 0, recovering = 0, TERROR = 2, EOF = 1;
    var args = lstack.slice.call(arguments, 1);
    var lexer = Object.create(this.lexer);
    var sharedState = { yy: {} };
    for (var k in this.yy) {
        if (Object.prototype.hasOwnProperty.call(this.yy, k)) {
            sharedState.yy[k] = this.yy[k];
        }
    }
    lexer.setInput(input, sharedState.yy);
    sharedState.yy.lexer = lexer;
    sharedState.yy.parser = this;
    if (typeof lexer.yylloc == 'undefined') {
        lexer.yylloc = {};
    }
    var yyloc = lexer.yylloc;
    lstack.push(yyloc);
    var ranges = lexer.options && lexer.options.ranges;
    if (typeof sharedState.yy.parseError === 'function') {
        this.parseError = sharedState.yy.parseError;
    } else {
        this.parseError = Object.getPrototypeOf(this).parseError;
    }
    function popStack(n) {
        stack.length = stack.length - 2 * n;
        vstack.length = vstack.length - n;
        lstack.length = lstack.length - n;
    }
    _token_stack:
        var lex = function () {
            var token;
            token = lexer.lex() || EOF;
            if (typeof token !== 'number') {
                token = self.symbols_[token] || token;
            }
            return token;
        };
    var symbol, preErrorSymbol, state, action, a, r, yyval = {}, p, len, newState, expected;
    while (true) {
        state = stack[stack.length - 1];
        if (this.defaultActions[state]) {
            action = this.defaultActions[state];
        } else {
            if (symbol === null || typeof symbol == 'undefined') {
                symbol = lex();
            }
            action = table[state] && table[state][symbol];
        }
                    if (typeof action === 'undefined' || !action.length || !action[0]) {
                var errStr = '';
                expected = [];
                for (p in table[state]) {
                    if (this.terminals_[p] && p > TERROR) {
                        expected.push('\'' + this.terminals_[p] + '\'');
                    }
                }
                if (lexer.showPosition) {
                    errStr = 'Parse error on line ' + (yylineno + 1) + ':\n' + lexer.showPosition() + '\nExpecting ' + expected.join(', ') + ', got \'' + (this.terminals_[symbol] || symbol) + '\'';
                } else {
                    errStr = 'Parse error on line ' + (yylineno + 1) + ': Unexpected ' + (symbol == EOF ? 'end of input' : '\'' + (this.terminals_[symbol] || symbol) + '\'');
                }
                this.parseError(errStr, {
                    text: lexer.match,
                    token: this.terminals_[symbol] || symbol,
                    line: lexer.yylineno,
                    loc: yyloc,
                    expected: expected
                });
            }
        if (action[0] instanceof Array && action.length > 1) {
            throw new Error('Parse Error: multiple actions possible at state: ' + state + ', token: ' + symbol);
        }
        switch (action[0]) {
        case 1:
            stack.push(symbol);
            vstack.push(lexer.yytext);
            lstack.push(lexer.yylloc);
            stack.push(action[1]);
            symbol = null;
            if (!preErrorSymbol) {
                yyleng = lexer.yyleng;
                yytext = lexer.yytext;
                yylineno = lexer.yylineno;
                yyloc = lexer.yylloc;
                if (recovering > 0) {
                    recovering--;
                }
            } else {
                symbol = preErrorSymbol;
                preErrorSymbol = null;
            }
            break;
        case 2:
            len = this.productions_[action[1]][1];
            yyval.$ = vstack[vstack.length - len];
            yyval._$ = {
                first_line: lstack[lstack.length - (len || 1)].first_line,
                last_line: lstack[lstack.length - 1].last_line,
                first_column: lstack[lstack.length - (len || 1)].first_column,
                last_column: lstack[lstack.length - 1].last_column
            };
            if (ranges) {
                yyval._$.range = [
                    lstack[lstack.length - (len || 1)].range[0],
                    lstack[lstack.length - 1].range[1]
                ];
            }
            r = this.performAction.apply(yyval, [
                yytext,
                yyleng,
                yylineno,
                sharedState.yy,
                action[1],
                vstack,
                lstack
            ].concat(args));
            if (typeof r !== 'undefined') {
                return r;
            }
            if (len) {
                stack = stack.slice(0, -1 * len * 2);
                vstack = vstack.slice(0, -1 * len);
                lstack = lstack.slice(0, -1 * len);
            }
            stack.push(this.productions_[action[1]][0]);
            vstack.push(yyval.$);
            lstack.push(yyval._$);
            newState = table[stack[stack.length - 2]][stack[stack.length - 1]];
            stack.push(newState);
            break;
        case 3:
            return true;
        }
    }
    return true;
}};
/* generated by jison-lex 0.3.4 */
var lexer = (function(){
var lexer = ({

EOF:1,

parseError:function parseError(str, hash) {
        if (this.yy.parser) {
            this.yy.parser.parseError(str, hash);
        } else {
            throw new Error(str);
        }
    },

// resets the lexer, sets new input
setInput:function (input, yy) {
        this.yy = yy || this.yy || {};
        this._input = input;
        this._more = this._backtrack = this.done = false;
        this.yylineno = this.yyleng = 0;
        this.yytext = this.matched = this.match = '';
        this.conditionStack = ['INITIAL'];
        this.yylloc = {
            first_line: 1,
            first_column: 0,
            last_line: 1,
            last_column: 0
        };
        if (this.options.ranges) {
            this.yylloc.range = [0,0];
        }
        this.offset = 0;
        return this;
    },

// consumes and returns one char from the input
input:function () {
        var ch = this._input[0];
        this.yytext += ch;
        this.yyleng++;
        this.offset++;
        this.match += ch;
        this.matched += ch;
        var lines = ch.match(/(?:\r\n?|\n).*/g);
        if (lines) {
            this.yylineno++;
            this.yylloc.last_line++;
        } else {
            this.yylloc.last_column++;
        }
        if (this.options.ranges) {
            this.yylloc.range[1]++;
        }

        this._input = this._input.slice(1);
        return ch;
    },

// unshifts one char (or a string) into the input
unput:function (ch) {
        var len = ch.length;
        var lines = ch.split(/(?:\r\n?|\n)/g);

        this._input = ch + this._input;
        this.yytext = this.yytext.substr(0, this.yytext.length - len);
        //this.yyleng -= len;
        this.offset -= len;
        var oldLines = this.match.split(/(?:\r\n?|\n)/g);
        this.match = this.match.substr(0, this.match.length - 1);
        this.matched = this.matched.substr(0, this.matched.length - 1);

        if (lines.length - 1) {
            this.yylineno -= lines.length - 1;
        }
        var r = this.yylloc.range;

        this.yylloc = {
            first_line: this.yylloc.first_line,
            last_line: this.yylineno + 1,
            first_column: this.yylloc.first_column,
            last_column: lines ?
                (lines.length === oldLines.length ? this.yylloc.first_column : 0)
                 + oldLines[oldLines.length - lines.length].length - lines[0].length :
              this.yylloc.first_column - len
        };

        if (this.options.ranges) {
            this.yylloc.range = [r[0], r[0] + this.yyleng - len];
        }
        this.yyleng = this.yytext.length;
        return this;
    },

// When called from action, caches matched text and appends it on next action
more:function () {
        this._more = true;
        return this;
    },

// When called from action, signals the lexer that this rule fails to match the input, so the next matching rule (regex) should be tested instead.
reject:function () {
        if (this.options.backtrack_lexer) {
            this._backtrack = true;
        } else {
            return this.parseError('Lexical error on line ' + (this.yylineno + 1) + '. You can only invoke reject() in the lexer when the lexer is of the backtracking persuasion (options.backtrack_lexer = true).\n' + this.showPosition(), {
                text: "",
                token: null,
                line: this.yylineno
            });

        }
        return this;
    },

// retain first n characters of the match
less:function (n) {
        this.unput(this.match.slice(n));
    },

// displays already matched input, i.e. for error messages
pastInput:function () {
        var past = this.matched.substr(0, this.matched.length - this.match.length);
        return (past.length > 20 ? '...':'') + past.substr(-20).replace(/\n/g, "");
    },

// displays upcoming input, i.e. for error messages
upcomingInput:function () {
        var next = this.match;
        if (next.length < 20) {
            next += this._input.substr(0, 20-next.length);
        }
        return (next.substr(0,20) + (next.length > 20 ? '...' : '')).replace(/\n/g, "");
    },

// displays the character position where the lexing error occurred, i.e. for error messages
showPosition:function () {
        var pre = this.pastInput();
        var c = new Array(pre.length + 1).join("-");
        return pre + this.upcomingInput() + "\n" + c + "^";
    },

// test the lexed token: return FALSE when not a match, otherwise return token
test_match:function(match, indexed_rule) {
        var token,
            lines,
            backup;

        if (this.options.backtrack_lexer) {
            // save context
            backup = {
                yylineno: this.yylineno,
                yylloc: {
                    first_line: this.yylloc.first_line,
                    last_line: this.last_line,
                    first_column: this.yylloc.first_column,
                    last_column: this.yylloc.last_column
                },
                yytext: this.yytext,
                match: this.match,
                matches: this.matches,
                matched: this.matched,
                yyleng: this.yyleng,
                offset: this.offset,
                _more: this._more,
                _input: this._input,
                yy: this.yy,
                conditionStack: this.conditionStack.slice(0),
                done: this.done
            };
            if (this.options.ranges) {
                backup.yylloc.range = this.yylloc.range.slice(0);
            }
        }

        lines = match[0].match(/(?:\r\n?|\n).*/g);
        if (lines) {
            this.yylineno += lines.length;
        }
        this.yylloc = {
            first_line: this.yylloc.last_line,
            last_line: this.yylineno + 1,
            first_column: this.yylloc.last_column,
            last_column: lines ?
                         lines[lines.length - 1].length - lines[lines.length - 1].match(/\r?\n?/)[0].length :
                         this.yylloc.last_column + match[0].length
        };
        this.yytext += match[0];
        this.match += match[0];
        this.matches = match;
        this.yyleng = this.yytext.length;
        if (this.options.ranges) {
            this.yylloc.range = [this.offset, this.offset += this.yyleng];
        }
        this._more = false;
        this._backtrack = false;
        this._input = this._input.slice(match[0].length);
        this.matched += match[0];
        token = this.performAction.call(this, this.yy, this, indexed_rule, this.conditionStack[this.conditionStack.length - 1]);
        if (this.done && this._input) {
            this.done = false;
        }
        if (token) {
            return token;
        } else if (this._backtrack) {
            // recover context
            for (var k in backup) {
                this[k] = backup[k];
            }
            return false; // rule action called reject() implying the next rule should be tested instead.
        }
        return false;
    },

// return next match in input
next:function () {
        if (this.done) {
            return this.EOF;
        }
        if (!this._input) {
            this.done = true;
        }

        var token,
            match,
            tempMatch,
            index;
        if (!this._more) {
            this.yytext = '';
            this.match = '';
        }
        var rules = this._currentRules();
        for (var i = 0; i < rules.length; i++) {
            tempMatch = this._input.match(this.rules[rules[i]]);
            if (tempMatch && (!match || tempMatch[0].length > match[0].length)) {
                match = tempMatch;
                index = i;
                if (this.options.backtrack_lexer) {
                    token = this.test_match(tempMatch, rules[i]);
                    if (token !== false) {
                        return token;
                    } else if (this._backtrack) {
                        match = false;
                        continue; // rule action called reject() implying a rule MISmatch.
                    } else {
                        // else: this is a lexer rule which consumes input without producing a token (e.g. whitespace)
                        return false;
                    }
                } else if (!this.options.flex) {
                    break;
                }
            }
        }
        if (match) {
            token = this.test_match(match, rules[index]);
            if (token !== false) {
                return token;
            }
            // else: this is a lexer rule which consumes input without producing a token (e.g. whitespace)
            return false;
        }
        if (this._input === "") {
            return this.EOF;
        } else {
            return this.parseError('Lexical error on line ' + (this.yylineno + 1) + '. Unrecognized text.\n' + this.showPosition(), {
                text: "",
                token: null,
                line: this.yylineno
            });
        }
    },

// return next match that has a token
lex:function lex () {
        var r = this.next();
        if (r) {
            return r;
        } else {
            return this.lex();
        }
    },

// activates a new lexer condition state (pushes the new lexer condition state onto the condition stack)
begin:function begin (condition) {
        this.conditionStack.push(condition);
    },

// pop the previously active lexer condition state off the condition stack
popState:function popState () {
        var n = this.conditionStack.length - 1;
        if (n > 0) {
            return this.conditionStack.pop();
        } else {
            return this.conditionStack[0];
        }
    },

// produce the lexer rule set which is active for the currently active lexer condition state
_currentRules:function _currentRules () {
        if (this.conditionStack.length && this.conditionStack[this.conditionStack.length - 1]) {
            return this.conditions[this.conditionStack[this.conditionStack.length - 1]].rules;
        } else {
            return this.conditions["INITIAL"].rules;
        }
    },

// return the currently active lexer condition state; when an index argument is provided it produces the N-th previous condition state, if available
topState:function topState (n) {
        n = this.conditionStack.length - 1 - Math.abs(n || 0);
        if (n >= 0) {
            return this.conditionStack[n];
        } else {
            return "INITIAL";
        }
    },

// alias for begin(condition)
pushState:function pushState (condition) {
        this.begin(condition);
    },

// return the number of states currently on the stack
stateStackSize:function stateStackSize() {
        return this.conditionStack.length;
    },
options: {},
performAction: function anonymous(yy,yy_,$avoiding_name_collisions,YY_START) {
var YYSTATE=YY_START;
switch($avoiding_name_collisions) {
case 0:/* skip whitespace */
break;
case 1:return 16;
break;
case 2:return 18;
break;
case 3:return 21;
break;
case 4:return 13;
break;
case 5:return 11;
break;
case 6:return 7;
break;
case 7:return 23;
break;
case 8:return 14;
break;
case 9:return 'AS';
break;
case 10:return 54;
break;
case 11:return 19;
break;
case 12:return 25;
break;
case 13:return 47;
break;
case 14:return 46;
break;
case 15:return 32;
break;
case 16:return 35;
break;
case 17:return 51;
break;
case 18:return 30;
break;
case 19:return 37;
break;
case 20:return 38;
break;
case 21:return 49;
break;
case 22:return 28;
break;
case 23:return 8;
break;
case 24:return 10;
break;
case 25:return 31;
break;
case 26:return 34;
break;
case 27:return 40;
break;
case 28:return 42;
break;
case 29:/* IGNORE */
break;
case 30:/* IGNORE */
break;
case 31:return 33;
break;
case 32:return 26;
break;
case 33:return 53;
break;
case 34:return 'QUOTE';
break;
case 35:return 5;
break;
}
},
rules: [/^(?:\s+)/,/^(?:add)/,/^(?:set)/,/^(?:define)/,/^(?:pass)/,/^(?:scene)/,/^(?:export)/,/^(?:extends)/,/^(?:import)/,/^(?:as)/,/^(?:ogl.[a-zA-Z0-9]+)/,/^(?:[a-zA-Z_]+=)/,/^(?:[a-zA-Z]+ ?(?=->))/,/^(?:0x[0-9A-Fa-f]{8})/,/^(?:0x[0-9A-Fa-f]{6})/,/^(?:\-?[0-9]+(?:\.[0-9]+)?)/,/^(?:'[a-zA-Z0-9\._\/]*')/,/^(?:(true|false))/,/^(?:vec3)/,/^(?:deg)/,/^(?:rad)/,/^(?:\.[a-zA-Z0-9_]+)/,/^(?:[a-zA-Z0-9]+)/,/^(?:\{)/,/^(?:\})/,/^(?:\()/,/^(?:\))/,/^(?:\[)/,/^(?:\])/,/^(?:#.*)/,/^(?:[\/][*][^*]*[*]+([^\/*][^*]*[*]+)*[\/])/,/^(?:,)/,/^(?:->)/,/^(?:[\*\+\-\^\%\/])/,/^(?:')/,/^(?:$)/],
conditions: {"INITIAL":{"rules":[0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35],"inclusive":true}}
});
return lexer;
})();
parser.lexer = lexer;
function Parser () {
  this.yy = {};
}
Parser.prototype = parser;parser.Parser = Parser;
return new Parser;
})();


if (typeof require !== 'undefined' && typeof exports !== 'undefined') {
exports.parser = parser;
exports.Parser = parser.Parser;
exports.parse = function () { return parser.parse.apply(parser, arguments); };
exports.main = function commonjsMain (args) {
    if (!args[1]) {
        console.log('Usage: '+args[0]+' FILE');
        process.exit(1);
    }
    var source = require('fs').readFileSync(require('path').normalize(args[1]), "utf8");
    return exports.parser.parse(source);
};
if (typeof module !== 'undefined' && require.main === module) {
  exports.main(process.argv.slice(1));
}
}