module.exports = {
    "DRAG": 'drag',
    "KEYPRESS": 'keypress',
    "KEYDOWN": "keydown",
    "INTERVAL": "interval",
    "MOUSEWHEEL": "mousewheel",
    "BUTTON0": 0,
    "BUTTON1": 1,
    "BUTTON2": 2,
    "BUTTON3": 3,
    "BUTTON4": 4,
    "FRAME": 16,
    "DIRECTIONAL": 'directional',
    "AMBIENT": 'ambient',
    "POINT": 'point',
    "SELF": 0,
    "WORLD": 1,
}